### ISSUE TITLE
!!! lessc (less css compiler) is missing on your system. Please install it!

### ISSUE THREAD

**Issue by lvzaina** [mkschreder/juci#27]
"ubuntu-bootstrap.sh" files have not been updated
need
```
sudo npm install -g less
```

**Comment by mkschreder** [comment]
have updated now.

**Comment by mkschreder** [comment]
in v1.15.11rc6 branch..

**Comment by lvzaina** [comment]
"contributions"?
v1.15.11rc6 have not been updated

**Comment by mkschreder** [comment]
now everything has been merged into master..
