### ISSUE TITLE
General Help

### ISSUE THREAD

**Issue by gvalz** [mkschreder/juci#40]
Hello, i  would like to try juci but i’am not an expert and certainly i am doing something wrong and i can’t  reach the goal.

Could you explain schematically the procedure top down from cloning your git untill to build the package ?

I also would like to install on a 4 Mb flash router (TL-WR841N) do you think is it possible ? 

Thank you very much
regards
Giulio

**Comment by mkschreder** [comment]
4Mb is not enough. You will need to make your own slimmed down version. You
can do that by using jucid as backend and then creating your own slimmed
down frontend. Then it can fit.

Add feed as first feed in your feeds.conf (make sure you specify current
branch! Right now it is 2.16.04)
./scripts/feeds update juci
./scripts/feeds install -f -a -p juci
make menuconfig
select juci-full-openwrt
build.
