### ISSUE TITLE
Juci on WR940N, e.g. 4MB flash

### ISSUE THREAD

**Issue by SSadistic** [mkschreder/juci#56]
How can I compile it? I tried with minimalistic choose of things included and it still does't compile with a normal upgrade file, because of the size.. Any suggestions ?

**Comment by mkschreder** [comment]
No longer supported. Build your own minimalistic frontend on top of
orangerpcd backend. You may need to skip angular though and and opt for
simple html based frontend that has minimal javascript that interacts with
the websocket.
