### ISSUE TITLE
Compiling Juci on Ubuntu to be used on OpenWRT router

### ISSUE THREAD

**Issue by exander77** [mkschreder/juci#67]
I seem to have problem understanding how to build Juci on Ubuntu so I can use on my OpenWRT router as LuCI replacement.

Could you point me to the right direction?

**Comment by mkschreder** [comment]
You should build as part of openwrt. Check this script to see how to add
the necessary feed and select required packages:
https://github.com/mkschreder/juci-openwrt-feed/blob/master/openwrt-bootstrap.sh

There is also a uml (user mode linux) build script in the feed repo above
that will build openwrt as a native executable and also build a rootfs
image that you can pass to it and run openwrt as a linux process (uml image
is rather limited though)

**Comment by exander77** [comment]
There is no way to build it separately and install it from packages? It has some platform dependencies?

**Comment by exander77** [comment]
I tried to build juci repository and it went fine, it created bin directory with etc, sbin, usr, www, can I make a package and install this on my OpenWRT router?

**Comment by mkschreder** [comment]
You can of course. You just need to figure out the peculiarities of your
particular system yourself.
