### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by daofeng2015** [mkschreder/juci#69]
Is translation just like Luci? Other translators write good chaos! .

**Comment by mkschreder** [comment]
Yes exactly the same. All strings in the ui are stored in a separate po
database for each language. The source template from which you can update
each language is produced during build.

**Comment by daofeng2015** [comment]
Thank you, can you give Juci plus other default sha1um support, default no choice

**Comment by mkschreder** [comment]
I assume you found this:
https://github.com/mkschreder/juci-openwrt-feed/blob/master/openwrt-bootstrap.sh
