### ISSUE TITLE
I visit the home page and can not see anything. The homepage is blank.Also the console does not have any errors

### ISSUE THREAD

**Issue by anoopantony8** [mkschreder/juci#71]
I ran these script during the setup of JUCI-openwrt:
_build-uml-image.sh_
But i was unsuccessful in creation of the image in bin.But later on running the script a few times  i was able to generate the folder "bin", but was missing the uml image.I downloaded the missing images and ran the script again . Then i started the uml image and was succesful in logging into openwrt shell.I did the steps mentioned in your doc.The isssue am facing now is that when running juci-local-server am getting a white screen without any errors in the console

The router am using is "Dlink DSL-2730U"

**Comment by mkschreder** [comment]
Use openwrt-bootstrap script in the juci-openwrt-feed repo as reference.

**Comment by anoopantony8** [comment]
@mkschreder I have used that script

**Comment by djhamzas** [comment]
I have a same problem can any one help me , when i cheked with fireburg i found  the flowing errors ;

"NetworkError: 404 Not Found - http://192.168.1.168/websocket/"
Firefox ne peut établir de connexion avec le serveur à l’adresse ws://192.168.1.168/websocket/.
	

01-juci.js (ligne 56, col. 1718)
"NetworkError: 404 Not Found - http://192.168.1.168/fonts/fontawesome-webfont.ttf?v=4.3.0"


Help me please

**Comment by mkschreder** [comment]
If websocket url is not found it means you are using wrong lighttpd. Use
the one in the juci feed repo and make sure that default openwrt one is
overridden properly.
