### ISSUE TITLE
UCI failed!

### ISSUE THREAD

**Issue by TadeuGRibeiro** [mkschreder/juci#78]
Hi Martin,

Long time that I don't write to you... In past I got sucess with JUCI compiling with OpenWRT. Now I'm working with another project that I used LEDE, but now I got an erro with UCI, I read all topics in your GitHub and try all things that you suggest for this and don't works.... please, can you help me?

Thanks a lot.

![error_router](https://user-images.githubusercontent.com/21226402/27709799-d7dc0382-5cf3-11e7-908d-4ca02cafb17c.png)

**Comment by mkschreder** [comment]
check if RPC.uci.* methods exist (you can do so in the browser console).

**Comment by TadeuGRibeiro** [comment]
I did and got this result...

![screenshot_1](https://user-images.githubusercontent.com/21226402/27719839-89d00386-5d2b-11e7-94db-a84127612948.png)

**Comment by TadeuGRibeiro** [comment]
Hi Martin, any idea?

Tks.

**Comment by TadeuGRibeiro** [comment]
anyone?

**Comment by mkschreder** [comment]
Sorry to hear you haven't solved it yet. What kind of debugging have you
done yourself so far? This type of error is fairly common when openwrt repo
has not been setup correctly from the start. Did you follow roughly the
same process as outlined in juci-openwrt-feed docs example?

https://github.com/mkschreder/juci-openwrt-feed/blob/master/build-uml-image.sh

On 13 Jul 2017 05:11, "Tadeu Ribeiro" <notifications@github.com> wrote:

anyone?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mkschreder/juci/issues/78#issuecomment-314958271>, or mute
the thread

**Comment by TadeuGRibeiro** [comment]
It's OK. Now I have just Browser console, and I dont get nothing that I can use... I think that OpenWRT setup are right... but whats type of wrong setup I can do? Do you have any idea? I follow all steps of juci-openwrt-feeds, but same result... I try in other machine and same error.... I dont know how I can debug more deeply...

**Comment by mkschreder** [comment]
Keep in mind that you need to run make distclean before you do the
bootstrap. The bootstrap is necessary so you get correct versions of the
packages. I have it on my todo list right now to make juci build on latest
lede. I know there are a few problems that need to get fixed first.

**Comment by TadeuGRibeiro** [comment]
This is an noob question, but I have problem with this now.... if I run make distclean, before set my target and the run the file openwrt-bootstrap.sh, the make defconfig is executed and set my target to ar71xx... I dont know how I can change the files to solve this...

**Comment by mkschreder** [comment]
ar71xx is default openwrt target. The example script should set the target
to user-mode-linux (UML). You should select your own target using make
menuconfig. The openwrt-bootstrap.sh is just an example that shows you the
steps you need to take to ensure that you are using all the compatible
versions of packages. You probably should not use it as your main build
script without making some changes to it.

**Comment by TadeuGRibeiro** [comment]
Right, I see it now. Thks.
I tried rebuild step by step that documentation describe, but I got same problem: UCI failed to initialize!

I don't have any idea that I can do to solve this... :(

**Comment by mkschreder** [comment]
I just pushed latest feed. There was no problem with the feed other than
some packages needed to be update to latest version.

Try this on latest lede:
* add juci feed to feeds.conf
* ./scripts/feeds update -a
* ./scripts/feeds uninstall -a
* ./scripts/feeds install -fap juci
* ./scripts/feeds install -a
* select juci-full-openwrt in menuconfig
* make

I just tested this and it works just fine. Make sure you clear browser
cache too (you may have some broken version cached from before).

**Comment by mkschreder** [comment]
Ok! I think I see the same problem you have. It is caused because openwrt
rpcd crashes. Why I don't know yet. If you do /etc/init.d/rpcd restart you
should be able to access the ui.

**Comment by TadeuGRibeiro** [comment]
I tried run /etc/init.d/rpcd restart but nothing... Then I runned command ps to check which process are running and I got the results as below.

 /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
  765 root      4288 S    /usr/sbin/lighttpd -f /etc/lighttpd.conf
  869 root      1180 S    udhcpc -p /var/run/udhcpc-eth0.2.pid -s /lib/netifd/dhcp.script -f -t 0 -i eth0.2 -C
  889 root      1180 S <  /usr/sbin/ntpd -n -N -S /usr/sbin/ntpd-hotplug -p 0.openwrt.pool.ntp.org -p 1.openwrt.pool.ntp.org -p 2.openwrt.poo
  932 root      1180 S    udhcpc -p /var/run/udhcpc-apcli0.pid -s /lib/netifd/dhcp.script -f -t 0 -i apcli0 -C
 1016 root      6768 S    /usr/bin/orangerpcd -p /usr/lib/orange/api/
 1032 dnsmasq   1048 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /var/run/dnsmasq/dnsmasq.pid
 1113 root      1124 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
 1114 root      1184 S    -ash
 1143 root      1612 S    /sbin/rpcd

RPCD and OrangeRpcd is running....

**Comment by mkschreder** [comment]
So if you run "ubus list" you can see uci in the list but you still get UCI
failed to initialize in the browser console?

**Comment by TadeuGRibeiro** [comment]
I run ubus list and get this results....
![uci](https://user-images.githubusercontent.com/21226402/28266794-3ed72026-6acd-11e7-95fb-deac0b52ebc3.png)

**Comment by lfdominguez** [comment]
Is like this??? #80
