### ISSUE TITLE
Network connections page protocols error.

### ISSUE THREAD

**Issue by dbrody2004** [mkschreder/juci#83]
Getting the following error on this page.  I don't see protocols listed under ubus.

<img width="1236" alt="screen shot 2017-12-15 at 8 52 33 am" src="https://user-images.githubusercontent.com/4682241/34051998-6b1dce04-e175-11e7-86d0-ed1db0ee1f75.png">

<img width="584" alt="screen shot 2017-12-15 at 8 53 14 am" src="https://user-images.githubusercontent.com/4682241/34052014-78222a8c-e175-11e7-916a-2b9398924c7f.png">

**Comment by mkschreder** [comment]
./orange --host <your router> --username <juci user> --password <juci
login> list

This will list rpc objects exported by orangerpcd to juci.

you can find the client here:
https://github.com/mkschreder/orangerpcd/blob/master/orange

**Comment by mkschreder** [comment]
Check if $rpc.juci.network object exists. You can run orangerpcd with -vvvv
flag manually (instead of through init.d) to dump details of all requests
going back and forth and possibly figure out what the issue is.

**Comment by mkschreder** [comment]
A request arrives at lighttpd websocket proxy, gets forwarded to locally
running orangerpcd websocket server, then gets dispatched to appropriate
lua script within orangerpcd, then either through ubus command to ubus
object or directly back to the client with structured data from lua which
gets translated into json along the way.
