### ISSUE TITLE
juci project no more update?

### ISSUE THREAD

**Issue by RadioOperator** [mkschreder/juci#93]
Hi, any open source makes this JUCI works on latest openwrt version 21.02, please let me know, thanks.

I tried, but failed.

**Comment by sjsaes** [comment]
It doesn't seem like the developer is active anymore. I would consider JUCI as legacy software (Last release was in 2016, probably built and compiled with outdated software). I wouldn't expect an update anytime soon, however, the latest version seems to work fine. I've read up on JUCI a bit, and it seems that the dev used it for custom software for clients (AFAIK). I assume the dev doesn't need the custom software for clients anymore, meaning the dev has no reason to continue updating.

**Comment by RadioOperator** [comment]
[gargoyle](https://www.gargoyle-router.com/download.php) maybe an alternative.

**Comment by mkschreder** [comment]
> It doesn't seem like the developer is active anymore. I would consider JUCI as legacy software (Last release was in 2016, probably built and compiled with outdated software). I wouldn't expect an update anytime soon, however, the latest version seems to work fine. I've read up on JUCI a bit, and it seems that the dev used it for custom software for clients (AFAIK). I assume the dev doesn't need the custom software for clients anymore, meaning the dev has no reason to continue updating.

I simply stopped working on Web UI part of firmware development and had no reason to maintain this project.
